pub const OP_RETURN: u8 = 0x6a;
pub const MAIN_TO_SIDE_TX_REQUEST_COMMITMENT_HEADER: [u8; 4] = [0x53, 0x70, 0x72, 0x43];
pub const MAIN_TO_SIDE_TX_REQUEST_UPVOTE_COMMITMENT_HEADER: [u8; 4] = [0x53, 0x61, 0x63, 0x43];
pub const SIDE_TO_MAIN_TX_REQUEST_COMMITMENT_HEADER: [u8; 4] = [0xD4, 0x5A, 0xA9, 0x43];

pub const OP_RETURN_SIZE: usize = 1;
pub const COMMITMENT_HEADER_SIZE: usize = 4;
pub const SIDECHAIN_SLOT_NUMBER_SIZE: usize = 1;
pub const SIDECHAIN_NAME_SIZE: usize = 120;
pub const SIDECHAIN_PRIVATE_KEY_SIZE: usize = 32;
pub const UPVOTE_SIZE: usize = 25;
pub const BLINDED_TX_SIZE: usize = 32;

pub const OP_RETURN_START: usize = 0;
pub const OP_RETURN_END: usize = OP_RETURN_SIZE + OP_RETURN_START;
pub const COMMITMENT_HEADER_START: usize = OP_RETURN_END;
pub const COMMITMENT_HEADER_END: usize = COMMITMENT_HEADER_START + COMMITMENT_HEADER_SIZE;

// SidechainMessages::MainToSideTransactionRequest
pub const M_TO_S_TX_REQ_SIDECHAIN_SLOT_NUMBER_START: usize = COMMITMENT_HEADER_END;
pub const M_TO_S_TX_REQ_SIDECHAIN_SLOT_NUMBER_END: usize = M_TO_S_TX_REQ_SIDECHAIN_SLOT_NUMBER_START + SIDECHAIN_SLOT_NUMBER_SIZE;
pub const M_TO_S_TX_REQ_SIDECHAIN_NAME_START: usize = M_TO_S_TX_REQ_SIDECHAIN_SLOT_NUMBER_END;
pub const M_TO_S_TX_REQ_SIDECHAIN_NAME_END: usize = M_TO_S_TX_REQ_SIDECHAIN_NAME_START + SIDECHAIN_NAME_SIZE;
pub const M_TO_S_TX_REQ_SIDECHAIN_PRIVATE_KEY_START: usize = M_TO_S_TX_REQ_SIDECHAIN_NAME_END;
pub const M_TO_S_TX_REQ_SIDECHAIN_PRIVATE_KEY_END: usize = M_TO_S_TX_REQ_SIDECHAIN_PRIVATE_KEY_START + SIDECHAIN_PRIVATE_KEY_SIZE;

// SidechainMessages::MainToSideTransactionRequestUpvote
pub const M_TO_S_TX_REQ_UPVOTE_START: usize = COMMITMENT_HEADER_END;
pub const M_TO_S_TX_REQ_UPVOTE_END: usize = M_TO_S_TX_REQ_UPVOTE_START + UPVOTE_SIZE;

// SidechainMessages::SideToMainTransactionRequest
pub const S_TO_M_TX_REQ_SIDECHAIN_SLOT_NUMBER_START: usize = COMMITMENT_HEADER_END;
pub const S_TO_M_TX_REQ_SIDECHAIN_SLOT_NUMBER_END: usize = S_TO_M_TX_REQ_SIDECHAIN_SLOT_NUMBER_START + SIDECHAIN_SLOT_NUMBER_SIZE;
pub const S_TO_M_TX_REQ_BLINDED_TX_START: usize = S_TO_M_TX_REQ_SIDECHAIN_SLOT_NUMBER_END;
pub const S_TO_M_TX_REQ_BLINDED_TX_END: usize =  S_TO_M_TX_REQ_BLINDED_TX_START + BLINDED_TX_SIZE;
